### ISSUE TITLE
Timeout while processing message in webdriver.

### ISSUE THREAD

**Issue by speakless86** [speakless86/pokernowrobot#3]
```
INFO:root:['Js', '8s', 'As']
Exception in thread Thread-694:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/speakmore/Library/Python/3.8/lib/python/site-packages/socketio/client.py", line 705, in _handle_eio_message
    self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/Users/speakmore/Library/Python/3.8/lib/python/site-packages/socketio/client.py", line 581, in _handle_event
    r = self._trigger_event(data[0], namespace, *data[1:])
  File "/Users/speakmore/Library/Python/3.8/lib/python/site-packages/socketio/client.py", line 632, in _trigger_event
    return self.handlers[namespace]['*'](event, *args)
  File "/Users/speakmore/Projects/pokernowrobot/pokernow_listener.py", line 40, in catch_all
    processer.process(event, data)
  File "/Users/speakmore/Projects/pokernowrobot/pokernow_processor.py", line 60, in process
    self._poker_game.decide()
  File "/Users/speakmore/Projects/pokernowrobot/poker_game.py", line 89, in decide
    self._preflop()
  File "/Users/speakmore/Projects/pokernowrobot/poker_game.py", line 111, in _preflop
    fold(self._driver)
  File "/Users/speakmore/Projects/pokernowrobot/pokernow_control_utils.py", line 48, in fold
    fold_button = WebDriverWait(
  File "/Users/speakmore/Library/Python/3.8/lib/python/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
0   chromedriver                        0x00000001045c5a90 chromedriver + 3889808
1   chromedriver                        0x0000000104554b54 chromedriver + 3427156
2   chromedriver                        0x0000000104246238 chromedriver + 221752
3   chromedriver                        0x00000001042774c8 chromedriver + 423112
4   chromedriver                        0x00000001042a0944 chromedriver + 592196
5   chromedriver                        0x000000010426c54c chromedriver + 378188
6   chromedriver                        0x00000001045992f8 chromedriver + 3707640
7   chromedriver                        0x000000010459cea8 chromedriver + 3722920
8   chromedriver                        0x00000001045a33d8 chromedriver + 3748824
9   chromedriver                        0x000000010459d9a8 chromedriver + 3725736
10  chromedriver                        0x0000000104578de8 chromedriver + 3575272
11  chromedriver                        0x00000001045b7d1c chromedriver + 3833116
12  chromedriver                        0x00000001045b7e84 chromedriver + 3833476
13  chromedriver                        0x00000001045cc210 chromedriver + 3916304
14  libsystem_pthread.dylib             0x0000000187d0506c _pthread_start + 320
15  libsystem_pthread.dylib             0x0000000187cffda0 thread_start + 8

INFO:root:State changes from PokerGameState.FLOP to PokerGameState.PREFLOP
```

**Comment by speakless86** [comment]
Didn't see that after removing the sleeping time.
